DROP TABLE IF EXISTS district;
DROP TABLE IF EXISTS district_postal_code;
CREATE TABLE district (id INTEGER AUTO_INCREMENT, name VARCHAR(255) NOT NULL, PRIMARY KEY (id) );
CREATE TABLE district_postal_code (district_id INTEGER NOT NULL, postal_code INTEGER NOT NULL, PRIMARY KEY (postal_code,district_id) );
INSERT INTO district (id,name) VALUES (1,'Fuencarral - El Pardo ');
INSERT INTO district (id,name) VALUES (2,'Moncloa - Aravaca ');
INSERT INTO district (id,name) VALUES (3,'Tetuán');
INSERT INTO district (id,name) VALUES (4,'Hortaleza');
INSERT INTO district (id,name) VALUES (5,'Chamartín');
INSERT INTO district (id,name) VALUES (6,'Ciudad Lineal');
INSERT INTO district (id,name) VALUES (7,'Chamberí');
INSERT INTO district (id,name) VALUES (8,'Barrio de Salamanca');
INSERT INTO district (id,name) VALUES (9,'San Blas');
INSERT INTO district (id,name) VALUES (10,'Barajas');
INSERT INTO district (id,name) VALUES (11,'Centro');
INSERT INTO district (id,name) VALUES (12,'Retiro');
INSERT INTO district (id,name) VALUES (13,'Arganzuela');
INSERT INTO district (id,name) VALUES (14,'Moratalaz');
INSERT INTO district (id,name) VALUES (15,'Villaverde');
INSERT INTO district (id,name) VALUES (16,'Usera');
INSERT INTO district (id,name) VALUES (17,'Latina');
INSERT INTO district (id,name) VALUES (18,'Carabanchel');
INSERT INTO district (id,name) VALUES (19,'Vicálvaro');
INSERT INTO district (id,name) VALUES (20,'Puente de Vallecas ');
INSERT INTO district (id,name) VALUES (21,'Villa de Vallecas ');
INSERT INTO district_postal_code (district_id,postal_code) VALUES (1,28023);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (1,28029);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (1,28034);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (1,28035);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (1,28048);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (1,28049);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (1,28050);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (2,28011);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (2,28013);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (2,28023);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (2,28035);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (2,28039);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (2,28040);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (3,28020);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (3,28029);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (3,28039);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (3,28046);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (4,28033);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (4,28042);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (4,28043);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (4,28050);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (5,28002);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (5,28006);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (5,28016);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (5,28036);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (5,28046);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (6,28017);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (6,28027);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (6,28032);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (6,28033);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (6,28043);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (7,28003);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (7,28010);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (7,28015);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (7,28046);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (8,28001);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (8,28006);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (8,28007);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (8,28009);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (8,28028);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (8,28046);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (9,28022);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (9,28027);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (9,28032);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (9,28037);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (10,28042);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (10,28043);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (11,28004);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (11,28005);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (11,28012);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (11,28013);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (11,28014);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (11,28015);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (12,28007);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (12,28009);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (12,28014);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (13,28005);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (13,28012);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (13,28045);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (14,28030);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (15,28021);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (15,28041);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (16,28026);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (16,28041);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (17,28011);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (17,28024);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (17,28044);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (17,28047);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (17,28054);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (18,28019);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (18,28025);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (18,28044);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (18,28047);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (18,28054);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (19,28031);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (19,28032);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (19,28052);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (20,28018);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (20,28031);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (20,28038);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (20,28053);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (21,28031);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (21,28051);
INSERT INTO district_postal_code (district_id,postal_code) VALUES (21,28053);